import type { NextPage } from 'next'
import Head from 'next/head'
import {
  Mint,
  About,
  RoadMap,
  Footer
} from '../components'

const Home: NextPage = () => {

  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Your project name here</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mint />
      <About />
      <RoadMap />
      <Footer />
    </div>
  )
}

export default Home
